"""Seed data for AUTOMOTOS L.P."""

SEED_BUSINESSES = [
    {
        "name": "Taller El Fierro", "category": "mecanica", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111001",
        "description": "Mecanica general, diagnostico computarizado y service completo.",
        "services": ["Service", "Diagnostico", "Distribucion", "Frenos"],
        "highlighted": True, "rating": 4.8, "reviewsCount": 12,
        "photos": ["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80", "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Mecanica Los Hornos", "category": "mecanica", "vehicles": ["auto"],
        "zone": "Los Hornos", "whatsapp": "5492211111002",
        "description": "Especialistas en motores nafteros y diesel.",
        "services": ["Motor", "Embrague", "Inyeccion"],
        "highlighted": False, "rating": 4.5, "reviewsCount": 6,
        "photos": ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Moto Service City Bell", "category": "mecanica", "vehicles": ["moto"],
        "zone": "City Bell", "whatsapp": "5492211111003",
        "description": "Service integral de motos de todas las cilindradas.",
        "services": ["Service moto", "Cadena", "Carburacion"],
        "highlighted": True, "rating": 4.9, "reviewsCount": 20,
        "photos": ["https://images.unsplash.com/photo-1558981285-6f0c94958bb6?w=800&q=80", "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Chapa y Pintura Ramos", "category": "chapa_pintura", "vehicles": ["auto", "moto"],
        "zone": "Tolosa", "whatsapp": "5492211111004",
        "description": "Chapa, pintura horno y pulido profesional.",
        "services": ["Pintura horno", "Chapa", "Pulido", "Detallado"],
        "highlighted": False, "rating": 4.6, "reviewsCount": 9,
        "photos": ["https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Neumaticos del Sur", "category": "neumaticos", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111005",
        "description": "Venta y colocacion de cubiertas, alineacion y balanceo.",
        "services": ["Cubiertas", "Alineacion", "Balanceo"],
        "highlighted": True, "rating": 4.7, "reviewsCount": 14,
        "photos": ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Gomeria 24hs La Plata", "category": "neumaticos", "vehicles": ["auto"],
        "zone": "Villa Elisa", "whatsapp": "5492211111006",
        "description": "Auxilio de gomeria las 24 horas.",
        "services": ["Auxilio", "Parches", "Cubiertas"],
        "highlighted": False, "rating": 4.3, "reviewsCount": 4, "photos": [],
        "status": "approved",
    },
    {
        "name": "Electricidad del Automotor JR", "category": "electrica", "vehicles": ["auto", "moto"],
        "zone": "Berisso", "whatsapp": "5492211111007",
        "description": "Electricidad, alarmas y colocacion de estereos.",
        "services": ["Alternador", "Alarmas", "Estereo", "Cableado"],
        "highlighted": False, "rating": 4.4, "reviewsCount": 7,
        "photos": ["https://images.unsplash.com/photo-1632823471565-1ecdf5c6d7f9?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Optica y Alineacion Faro", "category": "optica", "vehicles": ["auto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111008",
        "description": "Pulido de opticas y regulacion de luces.",
        "services": ["Pulido optica", "Regulacion", "Xenon"],
        "highlighted": False, "rating": 4.2, "reviewsCount": 3, "photos": [],
        "status": "approved",
    },
    {
        "name": "Soldaduras Especiales GT", "category": "soldadura", "vehicles": ["auto", "moto"],
        "zone": "Ensenada", "whatsapp": "5492211111009",
        "description": "Soldadura de aluminio, TIG y estructuras.",
        "services": ["TIG", "Aluminio", "Estructuras"],
        "highlighted": False, "rating": 4.6, "reviewsCount": 5,
        "photos": ["https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Grua y Auxilio Mach", "category": "grua", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492216370108",
        "description": "Auxilio mecanico y traslados con grua plana.",
        "services": ["Grua plana", "Auxilio", "Traslados"],
        "highlighted": True, "rating": 4.8, "reviewsCount": 11,
        "photos": ["https://images.unsplash.com/photo-1562920618-5e5f7f3b7b6f?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Lavadero Brillo Total", "category": "lavadero", "vehicles": ["auto", "moto"],
        "zone": "Gonnet", "whatsapp": "5492211111011",
        "description": "Lavado premium, detailing y tratamiento ceramico.",
        "services": ["Lavado", "Detailing", "Ceramico", "Tapizados"],
        "highlighted": False, "rating": 4.5, "reviewsCount": 8,
        "photos": ["https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Personalizacion Custom Garage", "category": "personalizacion", "vehicles": ["auto", "moto"],
        "zone": "City Bell", "whatsapp": "5492211111012",
        "description": "Wrapping, vinilos, llantas y tuning estetico.",
        "services": ["Wrapping", "Vinilos", "Llantas", "Tuning"],
        "highlighted": True, "rating": 4.9, "reviewsCount": 16,
        "photos": ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80", "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "GNC Rapido 44", "category": "gnc", "vehicles": ["auto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111013",
        "description": "Instalacion y revision de equipos de GNC.",
        "services": ["Equipo GNC", "Oblea", "Revision"],
        "highlighted": False, "rating": 4.4, "reviewsCount": 6, "photos": [],
        "status": "approved",
    },
    {
        "name": "Importados Racing Parts", "category": "importadores", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111014",
        "description": "Repuestos importados y performance.",
        "services": ["Repuestos", "Performance", "Accesorios"],
        "highlighted": False, "rating": 4.7, "reviewsCount": 9,
        "photos": ["https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Gestoria del Automotor VTV", "category": "papeles_vtv", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111015",
        "description": "Tramites, transferencias y turnos VTV.",
        "services": ["Transferencias", "VTV", "Patentamiento", "Cedulas"],
        "highlighted": False, "rating": 4.3, "reviewsCount": 5, "photos": [],
        "status": "approved",
    },
    {
        "name": "Estudio Legal Ruta Segura", "category": "asesoria_legal", "vehicles": ["auto", "moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111016",
        "description": "Accidentes de transito, seguros y siniestros.",
        "services": ["Accidentes", "Seguros", "Siniestros", "Multas"],
        "highlighted": False, "rating": 4.6, "reviewsCount": 7, "photos": [],
        "status": "approved",
    },
    {
        "name": "Cascos & Indumentaria RideOn", "category": "cascos", "vehicles": ["moto"],
        "zone": "Casco Urbano", "whatsapp": "5492211111017",
        "description": "Cascos homologados, camperas y guantes.",
        "services": ["Cascos", "Camperas", "Guantes", "Botas"],
        "highlighted": True, "rating": 4.8, "reviewsCount": 13,
        "photos": ["https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?w=800&q=80"],
        "status": "approved",
    },
    {
        "name": "Seguridad y Airbag Center", "category": "seguridad_airbag", "vehicles": ["auto", "moto"],
        "zone": "Gonnet", "whatsapp": "5492211111018",
        "description": "Reparacion de airbags, cinturones y sistemas de seguridad.",
        "services": ["Airbag", "Cinturones", "Sensores", "Chalecos"],
        "highlighted": False, "rating": 4.5, "reviewsCount": 6,
        "photos": ["https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80"],
        "status": "approved",
    },
]

SEED_RADARS = [
    {"lat": -34.9200, "lng": -57.9450, "type": "fijo", "speed": 60, "description": "Av. 1 y 60", "community": False},
    {"lat": -34.9165, "lng": -57.9530, "type": "fijo", "speed": 40, "description": "Av. 7 y 44", "community": False},
    {"lat": -34.9280, "lng": -57.9470, "type": "movil", "speed": None, "description": "Av. 13 y 32", "community": False},
    {"lat": -34.8620, "lng": -58.0300, "type": "fijo", "speed": 80, "description": "Camino Centenario y 514", "community": False},
    {"lat": -34.9400, "lng": -57.9800, "type": "fijo", "speed": 40, "description": "Av. 66 y 143", "community": False},
    {"lat": -34.8700, "lng": -58.0100, "type": "movil", "speed": None, "description": "Camino Belgrano y 505", "community": False},
    {"lat": -34.9560, "lng": -57.9140, "type": "fijo", "speed": 60, "description": "Av. 122 y 60", "community": False},
    {"lat": -34.9350, "lng": -57.9900, "type": "fijo", "speed": 40, "description": "Av. 44 y 155", "community": False},
    {"lat": -34.9100, "lng": -58.0400, "type": "fijo", "speed": 120, "description": "Autopista km 45", "community": False},
    {"lat": -34.9050, "lng": -57.9550, "type": "movil", "speed": None, "description": "Av. 72 y 25", "community": False},
]

SEED_FUEL = [
    {"name": "YPF 7 y 44", "kind": "combustible", "brand": "YPF", "lat": -34.9160, "lng": -57.9540},
    {"name": "Shell 13 y 32", "kind": "combustible", "brand": "Shell", "lat": -34.9280, "lng": -57.9470},
    {"name": "Axion 1 y 60", "kind": "combustible", "brand": "Axion", "lat": -34.9210, "lng": -57.9450},
    {"name": "GNC Los Hornos", "kind": "gnc", "brand": "YPF Gas", "lat": -34.9400, "lng": -57.9700},
    {"name": "GNC City Bell", "kind": "gnc", "brand": "Refsol", "lat": -34.8700, "lng": -58.0450},
    {"name": "Carga EV Dardo Rocha", "kind": "carga", "brand": "EV Point", "lat": -34.9210, "lng": -57.9540},
    {"name": "Carga EV Shopping Dot", "kind": "carga", "brand": "EV Point", "lat": -34.8900, "lng": -58.0500},
    {"name": "Puma 122 y 60", "kind": "combustible", "brand": "Puma", "lat": -34.9560, "lng": -57.9140},
]

SEED_EVENTS = [
    {"title": "Expo Fierro La Plata", "date": "2026-08-15", "location": "Predio Ferial La Plata", "type": "expo", "description": "La expo mas grande del fierro platense: autos, motos y accesorios."},
    {"title": "Picada Legal Autodromo Roberto Mouras", "date": "2026-09-05", "location": "Autodromo Roberto Mouras", "type": "carrera", "description": "Picadas legales cronometradas para autos y motos."},
    {"title": "Encuentro Motero Costa Berisso", "date": "2026-07-20", "location": "Costanera de Berisso", "type": "encuentro", "description": "Rodada y mateada frente al rio."},
    {"title": "Junta de Clasicos City Bell", "date": "2026-10-10", "location": "Plaza City Bell", "type": "encuentro", "description": "Encuentro de autos clasicos y de coleccion."},
]

SEED_CAMERAS = [
    {"lat": -34.9165, "lng": -57.9530, "type": "velocidad", "address": "Av. 7 y 50", "direction": "sentido Centro"},
    {"lat": -34.9560, "lng": -57.9140, "type": "mixta", "address": "Av. 122 y 60", "direction": "ambos sentidos"},
    {"lat": -34.9190, "lng": -57.9490, "type": "semaforo", "address": "Diagonal 74 y 3", "direction": "sentido Plaza Italia"},
    {"lat": -34.8620, "lng": -58.0300, "type": "velocidad", "address": "Camino Centenario y 514", "direction": "sentido City Bell"},
    {"lat": -34.9260, "lng": -57.9990, "type": "velocidad", "address": "Av. 44 y 137", "direction": "sentido Olmos"},
    {"lat": -34.9330, "lng": -57.9470, "type": "mixta", "address": "Av. 13 y 66", "direction": "sentido Berisso"},
    {"lat": -34.9000, "lng": -57.9700, "type": "velocidad", "address": "Av. 520 y 122", "direction": "sentido Tolosa"},
    {"lat": -34.9400, "lng": -57.9800, "type": "semaforo", "address": "Av. 66 y 143", "direction": "sentido Los Hornos"},
]

SEED_PLACES = [
    {"name": "Hospital San Martin", "kind": "hospital", "zone": "Casco Urbano", "lat": -34.9186, "lng": -57.9530},
    {"name": "Hospital Rossi", "kind": "hospital", "zone": "Zona Hospitalaria", "lat": -34.9095, "lng": -57.9440},
    {"name": "Comisaria 1ra", "kind": "comisaria", "zone": "Casco Urbano", "lat": -34.9214, "lng": -57.9545},
    {"name": "Comisaria 2da", "kind": "comisaria", "zone": "Meridiano V", "lat": -34.9320, "lng": -57.9450},
]

SEED_SITES = [
    {"name": "Punto Motero Republica de los Ninos", "zone": "Gonnet", "enabled": True, "description": "Encuentro clasico de motos los domingos."},
    {"name": "Costanera de Berisso", "zone": "Berisso", "enabled": True, "description": "Rodada y mateada frente al rio."},
    {"name": "Plaza Moreno", "zone": "Casco Urbano", "enabled": False, "description": "Punto historico; por ahora sin permiso para juntadas."},
    {"name": "Bosque - Planetario", "zone": "Casco Urbano", "enabled": True, "description": "Vueltas y encuentro al atardecer."},
]

SEED_DESVIOS = [
    {"street": "Av. 7 e/ 40 y 42", "type": "obra", "description": "Repavimentacion, una sola mano habilitada.", "lat": -34.9130, "lng": -57.9490},
    {"street": "Diagonal 80 y 45", "type": "corte", "description": "Corte total por evento; usa Av. 1.", "lat": -34.9170, "lng": -57.9560},
    {"street": "Av. 32 y 19", "type": "desvio", "description": "Desvio por rotura de cano.", "lat": -34.9080, "lng": -57.9700},
    {"street": "Av. 13 y 44", "type": "obra", "description": "Obra de bicisenda, reduccion de carril.", "lat": -34.9210, "lng": -57.9470},
]
